# Schema for the configuration files of the Teamspeak Status Block.

ts_status_block.settings:
  type: config_object
  label: 'Teamspeak Status Block Settings'
  mapping:
    ip_message:
      type: label
      label: 'Ip address'
