# Schema for the configuration files of the Teamspeak Status Block.

ts_status_block.settings:
  type: config_object
  label: 'Teamspeak Status Block Settings'
  mapping:
    ip_message:
      type: label
      label: 'Ip address'
    port_message:
      type: label
      label: 'Port address'
    background:
      type: label
      label: 'Background'
    server_info_background:
      type: label
      label: 'Server info background'
    server_info_text:
      type: label
      label: 'Server info text'
    server_name_background:
      type: label
      label: 'Server name background'
    server_name_text:
      type: label
      label: 'Server name text'
    info_background:
      type: label
      label: 'Info background'
    channel_background:
      type: label
      label: 'Channel background'
    channel_text:
      type: label
      label: 'Channel text'
    username_background:
      type: label
      label: 'Username background'
    username_text:
      type: label
      label: 'Username text'
